@endpoint=https://gateway.thegraph.com/api/deployments/id/QmTZ8ejXJxRo7vDBS4uwqBeGoxLSWbhaA7oXa1RvxunLy7
@authorization=Bearer 944b560e76f53abf0739468966998887
@origin=https://thegraph.com

### track the overall volume and activity of pools across different factories
# The query retrieves information about the factories on Uniswap, which are essentially the smart contracts that manage the liquidity pools on the platform
# Bundles, which typically represent a grouping of related data like token prices or liquidity data in Uniswap. 
POST {{endpoint}}
accept: application/json, multipart/mixed
X-REQUEST-TYPE: GraphQL
authorization: {{authorization}}
origin: {{origin}}

query {
  factories(first: 5) {
    id
    poolCount
    txCount
    totalVolumeUSD
    totalVolumeETH
    totalFeesUSD
    totalFeesETH
    owner
  }
  bundles(first: 5) {
    id
    ethPriceUSD
  }
}

### get tokens
POST {{endpoint}}
accept: application/json, multipart/mixed
X-REQUEST-TYPE: GraphQL
authorization: Bearer 944b560e76f53abf0739468966998887
origin: https://thegraph.com

query {
  tokens(first: 5) {
    id
    symbol
    name
  } 
}

### get pools
POST {{endpoint}}
accept: application/json, multipart/mixed
X-REQUEST-TYPE: GraphQL
authorization: Bearer 944b560e76f53abf0739468966998887
origin: https://thegraph.com

query {
  pools(first: 5) {
    id
    createdAtTimestamp
    createdAtBlockNumber
    liquidity
  }
}

### calculate the fees
POST {{endpoint}}
accept: application/json, multipart/mixed
X-REQUEST-TYPE: GraphQL
authorization: Bearer 944b560e76f53abf0739468966998887
origin: https://thegraph.com

query {
  pools(first: 5) {
    id
    feesUSD
    token0 {
      id
      symbol
    }
    token1 {
      id
      symbol
    }
  }
}

### get the price range
POST {{endpoint}}
accept: application/json, multipart/mixed
X-REQUEST-TYPE: GraphQL
authorization: Bearer 944b560e76f53abf0739468966998887
origin: https://thegraph.com

query {
  transactions {
    id
    timestamp
    mints {
      pool {
        id
        token0 {
          symbol
        }
        token1 {
          symbol
        }
        feeTier
      }
      tickLower
      tickUpper
    }
    burns {
      pool {
        id
        token0 {
          symbol
        }
        token1 {
          symbol
        }
        feeTier
      }
      tickLower
      tickUpper
    }
  }
}

